###########################################################
###############   App Rules    ###########################
##########################################################

 [[appRule]]
 class = "firefox"
# instance = "st"
 #title = "brave"
 monitor = 1
 tags = [ 1 ]
 state = "normal" # normal, floating, and fullscreen are all valid.

[[appRule]]
 class = "discord"
# instance = "st"
 #title = "brave"
 monitor = 1
 tags = [ 2 ]
 state = "normal"  


 [[appRule]]
 class = "URxvt"
# instance = "st"
 #title = "brave"
 #monitor = 1
 #tags = [ 1 ]
 state = "floating"

# Start external programs
[[startProcess]]
command = "pkill nimdow"
keys = [ "q" ]
modifiers = [ "super", "shift" ]

[[startProcess]]
command = "$BROWSER"
keys = [ "w" ]
modifiers = [ "super" ]

# Example: Start process when region is clicked, see github wiki for what constitutes a region
# [[startProcess]]
# command = "notify-send \"Id: %1, rx: %2, cx: %4, w: %6\""
# clickRegion = 0

[autostart]
exec = [
  "setbg",    # Set the background
  "xsetroot -cursor_name left_ptr",
  "xset r rate 400 30",  # Speed xrate up
#  "unclutter",   # Remove mouse when idle
#  "xset s off -dpms",
  "pidof -q compfy || compfy --config $HOME/.config/compfy.conf",
#  "dunst",                 # dunst for notifications
  "nm-applet",
  "/nix/store/$(ls -la /nix/store | grep 'mate-polkit' | grep '4096' | awk '{print $9}' | sed -n '$p')/libexec/polkit-mate-authentication-agent-1",
  "sxhkd -c ~/.config/nimdow/sxhkdrc",
  "slstatus",
  #"st",
]

[settings]
  # Window settings
  borderWidth = 6
  borderColorUnfocused = "#000000"
  borderColorFocused = "#2e8b57"
  borderColorUrgent = "#ff5555"
  # Bar settings
  barHeight = 42
  windowTitlePosition = "left"
  barBackgroundColor = "#1a1a1a"
  barForegroundColor = "#c3cdc8"
  barSelectionColor = "#50fa7b"
  barUrgentColor = "#ff5555"
  barFonts = [
    "JetBrains Mono Nerd Font:size=12:antialias=true",
    "JoyPixels:size=12:antialias=true:autohint=true",
  ]
	# Layout settings
  gapSize = 0
	resizeStep = 5
  # General settings
  loggingEnabled = false
  #reverseTagScrolling = false


#################################################
###############  Window manager controls  #######
#################################################


  [controls.reloadConfig]
  keys = [ "r" ]
  modifiers = [ "super", "shift" ]

  [controls.focusPrevious]
  keys = [ "k" ]
  modifiers = [ "super" ]

  [controls.focusNext]
  keys = [ "j" ]
  modifiers = [ "super" ]

  [controls.moveWindowPrevious]
  keys = [ "k" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowNext]
  keys = [ "j" ]
  modifiers = [ "super", "shift" ]

  [controls.toggleFullscreen]
  keys = [ "f" ]
  modifiers = [ "super" ]

  [controls.destroySelectedWindow]
  keys = [ "q" ]
  modifiers = [ "super"]

  [controls.goToPreviousTag]
  keys = [ "w" ]
  modifiers = [ "super", "alt" ]

  [controls.moveWindowToPreviousTag]
  keys = [ "h" ]
  modifiers = [ "super", "alt" ]

  [controls.focusPreviousMonitor]
  keys = [ "comma" ]
  modifiers = [ "super" ]

  [controls.focusNextMonitor]
  keys = [ "period" ]
  modifiers = [ "super" ]

  [controls.moveWindowToPreviousMonitor]
  keys = [ "comma" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowToNextMonitor]
  keys = [ "period" ]
  modifiers = [ "super", "shift" ]

  [controls.increaseMasterCount]
  keys = [ "z" ]
  modifiers = [ "super" ]

  [controls.decreaseMasterCount]
  keys = [ "x" ]
  modifiers = [ "super" ]

  [controls.toggleFloating]
  keys = [ "space" ]
  modifiers = [ "super" ]

  [controls.jumpToUrgentWindow]
  keys = [ "u" ]
  modifiers = [ "super" ]

  [controls.goToTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super" ]

  [controls.goToLeftTag]
  keys = [ "Left" ]
  modifiers = [ "super" ]

  [controls.goToRightTag]
  keys = [ "Right" ]
  modifiers = [ "super" ]

  [controls.moveWindowToTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowToLeftTag]
  keys = [ "Left" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowToRightTag]
  keys = [ "Right" ]
  modifiers = [ "super", "shift" ]

  [controls.toggleTagView]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "control" ]

  [controls.toggleWindowTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "shift", "control" ]

	[controls.increaseMasterWidth]
	keys = [ "l" ]
	modifiers = [ "super" ]

	[controls.decreaseMasterWidth]
	keys = [ "h" ]
	modifiers = [ "super" ]

  [controls.moveWindowToScratchpad]
  keys = [ "s" ]
  modifiers = [ "super", "shift" ]

  [controls.popScratchpad]
  keys = [ "s" ]
  modifiers = [ "super" ]

#################################################
############### Example monitor settings ########
#################################################

[monitors]
  [monitors.default.tags]
  1.displayString = " "
  2.displayString = " "
  3.displayString = " "
  4.displayString = " "
  5.displayString = " "
  6.displayString = " "
  7.displayString = " "
  8.displayString = " "
  9.displayString = " "

  [monitors.1.tags]
  # 2.displayString = "two"
  # Set the number of master windows per-monitor.
   all.numMasterWindows = 2
  # Set the number of master windows per-tag.
  # 2.numMasterWindows = 1

  # [monitors.2.tags]
  # 2.displayString = "too"

